[package]
name = "fetcher"
description = "Fetch stuff and send stuff"
version = "0.5.1"
license = "MPL-2.0"
repository = "https://github.com/SergeyKasmy/fetcher"
edition = "2021"

[profile.release]
lto = "thin"

[dependencies]
ammonia = "3.1.4"
anyhow = "1.0.55"
async-trait = "0.1.52"
chrono = "0.4.19"
egg-mode = { version = "0.16.0", features = ["rustls"], default-features = false }
figment = { version = "0.10.6", features = ["yaml"] }
futures = "0.3.21"
glob = "0.3.0"
# NOTE: 0.22 is a hard requirement by soup, make sure not to update it when doing cargo upgrade
html5ever = "0.22"
# imap = { version = "3.0.0-alpha.4", features = [ "rustls-tls" ], default-features = false }
imap = { version = "3.0.0-alpha.6", features = [ "rustls-tls" ], default-features = false }
itertools = "0.10.3"
mailparse = "0.13.8"
reqwest = { version = "0.11.9", features = ["rustls-tls"], default-features = false }
rss = "2.0.0"
serde = { version = "1.0.136", features = [ "derive" ] }
serde_json = "1.0.79"
serde_yaml = "0.8.23"
signal-hook = "0.3.13"
signal-hook-tokio = { version = "0.3.1", features = ["futures-v0_3"] }
soup = "0.5.1"
teloxide = { version = "0.7.0", features = ["rustls", "ctrlc_handler"], default-features = false }	# TODO: why is ctrlc_handler required anyway?
thiserror = "1.0.30"
tokio = { version = "1.17.0", features = ["full"] }
tracing = "0.1.31"
tracing-futures = "0.2.5"
tracing-subscriber = { version = "0.3.9", features = ["env-filter", "tracing-log"] }
url = "2.2.2"
xdg = "2.4.1"

[build-dependencies]
vergen = { version = "7.0.0", features = [ "git" ], default-features = false }
