[package]
name = "news-reader"
version = "0.1.0"
edition = "2018"

[profile.release]
lto = true
codegen-units = 1

[dependencies]
anyhow = "1.0.48"
async-trait = "0.1.51"
egg-mode = "0.16.0"
futures = "0.3.18"
log = "0.4.14"
pretty_env_logger = "0.4.0"
reqwest = "0.11.6"
rss = "2.0.0"
signal-hook = "0.3.10"
signal-hook-tokio = { version = "0.3.0", features = ["futures-v0_3"] }
teloxide = { version = "0.5.3", features = ["throttle"] }
thiserror = "1.0.30"
tokio = { version = "1.14.0", features = ["full"] }
