[package]
name = "fetcher"
description = "Fetch stuff and send stuff"
version = "0.6.0"
license = "MPL-2.0"
repository = "https://github.com/SergeyKasmy/fetcher"
edition = "2021"

[profile.release]
lto = "thin"

[dependencies]
ammonia = "3.2.0"
async-trait = "0.1.56"
chrono = "0.4.19"
color-eyre = "0.6.1"
egg-mode = { version = "0.16.0", features = ["rustls"], default-features = false }
figment = { version = "0.10.6", features = ["yaml"] }
futures = "0.3.21"
glob = "0.3.0"
# NOTE: 0.22 is a hard requirement by soup, make sure not to update it when doing cargo upgrade
html5ever = "0.22"
imap = { version = "3.0.0-alpha.7", features = [ "rustls-tls" ], default-features = false }
itertools = "0.10.3"
mailparse = "0.13.8"
reqwest = { version = "0.11.11", features = ["rustls-tls"], default-features = false }
rss = "2.0.1"
serde = { version = "1.0.138", features = [ "derive" ] }
serde_json = "1.0.82"
serde_yaml = "0.8.24"
signal-hook = "0.3.14"
signal-hook-tokio = { version = "0.3.1", features = ["futures-v0_3"] }
soup = "0.5.1"
teloxide = { version = "0.9.2", features = ["rustls", "ctrlc_handler"], default-features = false }	# TODO: why is ctrlc_handler required anyway?
thiserror = "1.0.31"
tokio = { version = "1.19.2", features = ["full"] }
tracing = "0.1.35"
tracing-futures = "0.2.5"
tracing-subscriber = { version = "0.3.14", features = ["env-filter", "tracing-log"] }
url = "2.2.2"
xdg = "2.4.1"

[build-dependencies]
vergen = { version = "7.2.1", features = [ "git" ], default-features = false }
