[package]
name = "fetcher"
version = "0.2.1"
edition = "2021"

[profile.release]
lto = "thin"
#lto = true
#codegen-units = 1

[dependencies]
ammonia = "3.1.3"
anyhow = "1.0.53"
async-trait = "0.1.52"
egg-mode = "0.16.0"
futures = "0.3.19"
imap = "2.4.1"
mailparse = "0.13.8"
native-tls = "0.2.8"
reqwest = "0.11.9"
rss = "2.0.0"
serde = { version = "1.0.136", features = [ "derive" ] }
serde_json = "1.0.78"
signal-hook = "0.3.13"
signal-hook-tokio = { version = "0.3.1", features = ["futures-v0_3"] }
teloxide = { version = "0.5.3", features = ["throttle"] }
thiserror = "1.0.30"
tokio = { version = "1.16.1", features = ["full"] }
toml = "0.5.8"
tracing = "0.1.29"
tracing-futures = "0.2.5"
tracing-log = "0.1.2"
tracing-subscriber = "0.3.7"
xdg = "2.4.0"

[features]
