
[package]
name = "fetcher"
description = "Fetch stuff and send stuff"
# don't forget to bump major version to better follow semver, dummy
version = "0.2.6"
license = "MPL-2.0"
repository = "https://github.com/SergeyKasmy/fetcher"
edition = "2021"

[profile.release]
lto = "thin"

[dependencies]
ammonia = "3.1.3"
anyhow = "1.0.53"
async-trait = "0.1.52"
egg-mode = { version = "0.16.0", features = ["rustls"], default-features = false }
futures = "0.3.21"
imap = { version = "3.0.0-alpha.4", features = [ "rustls-tls" ], default-features = false }
mailparse = "0.13.8"
reqwest = { version = "0.11.9", features = ["rustls-tls"], default-features = false }
rss = "2.0.0"
serde = { version = "1.0.136", features = [ "derive" ] }
serde_json = "1.0.78"
signal-hook = "0.3.13"
signal-hook-tokio = { version = "0.3.1", features = ["futures-v0_3"] }
teloxide = { version = "0.7.0", features = ["rustls", "ctrlc_handler"], default-features = false }	# TODO: why is ctrlc_handler required anyway?
thiserror = "1.0.30"
tokio = { version = "1.16.1", features = ["full"] }
toml = "0.5.8"
tracing = "0.1.30"
tracing-futures = "0.2.5"
tracing-log = "0.1.2"
tracing-subscriber = "0.3.8"
url = "2.2.2"
xdg = "2.4.0"
