[package]
name = "fetcher"
description = "Fetch stuff and send stuff"
version = "0.9.1"
license = "MPL-2.0"
repository = "https://github.com/SergeyKasmy/fetcher"
edition = "2021"

[dependencies]
fetcher-core = { version = "0.9.1", path = "../fetcher-core" }
color-eyre = "0.6.2"
chrono = "0.4.22"
figment = { version = "0.10.6", features = ["yaml"] }
futures = "0.3.21"
glob = "0.3.0"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"
signal-hook = "0.3.14"
signal-hook-tokio = { version = "0.3.1", features = ["futures-v0_3"] }
tokio = { version = "1.20.1", features = ["rt-multi-thread", "macros"] }
tracing = "0.1.36"
tracing-journald = "0.3.0"
tracing-subscriber = { version = "0.3.15", features = ["env-filter", "tracing-log", "time", "local-time"] }
xdg = "2.4.1"
url = "2.2.2"
thiserror = "1.0.32"

[build-dependencies]
vergen = { version = "7.3.2", features = ["git"], default-features = false }
