[package]
name = "fetcher"
description = "Fetch stuff and send stuff"
version = "0.10.0"
license = "MPL-2.0"
repository = "https://github.com/SergeyKasmy/fetcher"
edition = "2021"

[dependencies]
fetcher-core = { version = "0.10.0", path = "../fetcher-core" }
fetcher-config = { version = "0.10.0", path = "../fetcher-config" }
color-eyre = "0.6.2"
figment = { version = "0.10.8", features = ["yaml"] }
futures = "0.3.24"
glob = "0.3.0"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.86"
signal-hook = "0.3.14"
signal-hook-tokio = { version = "0.3.1", features = ["futures-v0_3"] }
tokio = { version = "1.21.2", features = ["rt-multi-thread", "macros"] }
tracing = "0.1.37"
tracing-journald = "0.3.0"
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "tracing-log", "time", "local-time"] }
xdg = "2.4.1"
argh = "0.1.9"
nix = { version = "0.25.0", default-features = false, features = ["user"] }

[build-dependencies]
vergen = { version = "7.4.2", features = ["git"], default-features = false }
