[package]
name = "fetcher"
description = "Fetch stuff and send stuff"
version = "0.7.0"
license = "MPL-2.0"
repository = "https://github.com/SergeyKasmy/fetcher"
edition = "2021"

[dependencies]
fetcher-core = { path = "../fetcher-core" }
color-eyre = "0.6.1"
figment = { version = "0.10.6", features = ["yaml"] }
futures = "0.3.21"
glob = "0.3.0"
serde = "1.0.138"
serde_json = "1.0.82"
signal-hook = "0.3.14"
signal-hook-tokio = { version = "0.3.1", features = ["futures-v0_3"] }
teloxide = { version = "0.9.2", features = ["rustls", "ctrlc_handler"], default-features = false }	# TODO: why is ctrlc_handler required anyway?
tokio = { version = "1.19.2", features = ["full"] }
tracing = "0.1.35"
tracing-futures = "0.2.5"
tracing-journald = "0.3.0"
tracing-subscriber = { version = "0.3.14", features = ["env-filter", "tracing-log", "time", "local-time"] }
xdg = "2.4.1"

[build-dependencies]
vergen = { version = "7.2.1", features = [ "git" ], default-features = false }
