[package]
name = "fetcher-config"
description = "fetcher config format and serialization/deserialization"
version = "0.13.1"
license = "MPL-2.0"
repository = "https://github.com/SergeyKasmy/fetcher"
edition = "2021"

[dependencies]
fetcher-core = { version = "0.13.1", path = "../fetcher-core" }

chrono = "0.4.24"
serde = { version = "1.0.163", features = ["derive"] }
thiserror = "1.0.40"
tokio = "1.28.1"
tracing = "0.1.37"
url = "2.3.1"
serde_with = "3.0.0"
duration-str = { version = "0.5.0", default-features = false }
itertools = "0.10.5"
tap = "1.0.1"
