[package]
name = "fetcher-config"
description = "fetcher config"
version = "0.11.1"
license = "MPL-2.0"
repository = "https://github.com/SergeyKasmy/fetcher"
edition = "2021"

[dependencies]
fetcher-core = { version = "0.11.1", path = "../fetcher-core" }

chrono = "0.4.23"
serde = { version = "1.0.152", features = ["derive"] }
thiserror = "1.0.38"
tokio = "1.25.0"
tracing = "0.1.37"
url = "2.3.1"
serde_with = "2.2.0"
duration-str = { version = "0.5.0", default-features = false }
