[package]
name = "fetcher-core"
description = "Core fetcher functionality"
version = "0.7.0"
license = "MPL-2.0"
repository = "https://github.com/SergeyKasmy/fetcher"
edition = "2021"

[dependencies]
ammonia = "3.2.0"
async-trait = "0.1.56"
chrono = "0.4.19"
egg-mode = { version = "0.16.0", features = ["rustls"], default-features = false }
futures = "0.3.21"
# NOTE: 0.22 is a hard requirement by soup, make sure not to update it when doing cargo upgrade
html5ever = "0.22"
imap = { version = "3.0.0-alpha.7", features = [ "rustls-tls" ], default-features = false }
itertools = "0.10.3"
mailparse = "0.13.8"
once_cell = "1.13.0"
reqwest = { version = "0.11.11", features = ["rustls-tls", "gzip"], default-features = false }
rss = "2.0.1"
serde = { version = "1.0.138", features = [ "derive" ] }
serde_json = "1.0.82"
soup = "0.5.1"
teloxide = { version = "0.9.2", features = ["rustls", "ctrlc_handler"], default-features = false }	# TODO: why is ctrlc_handler required anyway?
thiserror = "1.0.31"
tokio = { version = "1.19.2", features = ["full"] }
tracing = "0.1.35"
url = "2.2.2"
xdg = "2.4.1"	# FIXME: temporary, move to the binary
