[package]
name = "fetcher-core"
description = "Core fetcher functionality"
version = "0.11.1"
license = "MPL-2.0"
repository = "https://github.com/SergeyKasmy/fetcher"
edition = "2021"

[dependencies]
async-trait = "0.1.64"
chrono = "0.4.23"
derive_more = "0.99.17"
egg-mode = { version = "0.16.1", features = ["rustls"], default-features = false }
either = "1.8.1"
feed-rs = "1.2.0"
futures = "0.3.26"
imap = { version = "3.0.0-alpha.10", features = [ "rustls-tls" ], default-features = false }
itertools = "0.10.5"
mailparse = "0.14.0"
once_cell = "1.17.0"
regex = "1.7.1"
reqwest = { version = "0.11.14", features = ["rustls-tls", "gzip"], default-features = false }
roux = { version = "2.2.5", default-features = false, features = ["rustls"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
soup-kuchiki = "0.5.0"
tap = "1.0.1"
teloxide = { version = "0.12.0", features = ["rustls", "throttle"], default-features = false }
thiserror = "1.0.38"
tokio = { version = "1.25.0", features = ["fs", "io-std"] }
tracing = "0.1.37"
url = "2.3.1"

[dev-dependencies]
assert_matches = "1.5"
